source 'https://rubygems.org'

gem 'rails', '4.2.0'
gem 'sqlite3'

gem 'devise'
gem 'doorkeeper'

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'

  gem 'pry-rails'
  gem 'pry-doc'
  gem 'pry-stack_explorer'
  gem 'pry-byebug'

  gem 'quiet_assets'

  gem 'hirb'
  gem 'hirb-unicode'

end
group :development do
  gem 'letter_opener_web'
end
